### ISSUE TITLE
please consider adding `requirements.txt` or `pyproject.toml` with pinned dependencies

### ISSUE THREAD

**Issue by kodzonko** [ajpar94/spotify-youtube-playlist-converter#1]
Please add dependencies with appropriate versions if this script is meant for public use. I tried installing the latest versions (currently it's `google-api-python-client==2.129.0`, `google_auth_oauthlib==1.2.0` and `requests==2.32.2`)

but get the error:
```traceback
Traceback (most recent call last):
  File "C:\Users\janwa\Downloads\spotify-youtube-playlist-converter-master\convert_playlist.py", line 181, in <module>
    cp = ConvertPlaylist()
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\janwa\Downloads\spotify-youtube-playlist-converter-master\convert_playlist.py", line 24, in __init__
    self.youtube = self.get_youtube_client()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janwa\Downloads\spotify-youtube-playlist-converter-master\convert_playlist.py", line 94, in get_youtube_client
    credentials = flow.run_console()
                  ^^^^^^^^^^^^^^^^
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
```

knowing google's approach they probably changed the API and dropped backwards compatibility.

**Comment by ajpar94** [comment]
Sorry, I haven't worked on this in a long time. Will let you know, once I have looked into it
